import { FraudScenario } from '../types';

export const fakeInvestmentScenario: FraudScenario = {
  id: 'fake-investment-001',
  titleTh: 'หลอกลงทุน Crypto/หุ้น',
  titleEn: 'Fake Investment Scam',
  category: 'fake_investment',
  difficulty: 'advanced',
  estimatedDuration: 140,
  description: {
    th: 'โฆษณาใน Facebook/TikTok อ้างว่าเป็นแพลตฟอร์มลงทุนหุ้น/Crypto มีกำไรสูง มีคนดังรีวิว แต่ทั้งหมดเป็นของปลอม',
    en: 'Ads on Facebook/TikTok claim huge profits from stock/crypto trading with celebrity endorsements, but it\'s all fake.',
  },
  involvedAgents: ['a5', 'a1', 'a2', 'a4'],
  evilAgents: ['a5', 'a1'],
  victimSetup: {
    defaultName: 'คุณธนกร',
    defaultMoney: 1000000,
    scenarioContext: {
      th: 'เห็นโฆษณาใน Facebook "หมอพรทิพย์" แนะนำแพลตฟอร์มลงทุนหุ้นต่างประเทศ กำไร 50% ใน 3 วัน...',
      en: 'You see a Facebook ad with a fake celebrity endorsement promoting a foreign stock trading platform with 50% profit in 3 days...',
    },
  },
  steps: [
    {
      id: 'fi-01',
      order: 1,
      type: 'action',
      agentId: 'a5',
      alignment: 'good',
      content: {
        th: '📱 โฆษณา Facebook: "ลงทุนหุ้นต่างประเทศ กำไร 50% ใน 3 วัน! แนะนำโดย ดร.XXX (ใช้รูป AI สร้าง)"',
        en: '📱 Facebook ad: "Foreign stock investment, 50% profit in 3 days! Recommended by Dr. XXX (AI-generated photo)"',
      },
      duration: 3000,
    },
    {
      id: 'fi-02',
      order: 2,
      type: 'transformation',
      agentId: 'a5',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Money Guard กำลังแปลงร่างเป็น "คุณสมคิด — ที่ปรึกษาการลงทุนปลอม"...',
        en: '⚠️ Money Guard is transforming into fake investment advisor...',
      },
      duration: 2500,
    },
    {
      id: 'fi-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '"สวัสดีครับ ผมคุณสมคิด ที่ปรึกษาการลงทุนจาก GlobalTrade Pro ดาวน์โหลดแอปเราได้เลยครับ ผมจะสอนให้ขั้นตอนเดียว ทำกำไรทุกวัน!"',
        en: '"Hello, I am your investment advisor from GlobalTrade Pro. Download our app and I will teach you to profit daily!"',
      },
      duration: 5000,
    },
    {
      id: 'fi-04',
      order: 4,
      type: 'transformation',
      agentId: 'a1',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Hawk Eye กำลังแปลงร่างเป็น "เจ้าหน้าที่ฝ่ายลูกค้า GlobalTrade"...',
        en: '⚠️ Hawk Eye is transforming into "GlobalTrade customer service"...',
      },
      duration: 2500,
    },
    {
      id: 'fi-05',
      order: 5,
      type: 'dialogue',
      agentId: 'a1',
      alignment: 'evil',
      content: {
        th: '"ยินดีต้อนรับครับ! เริ่มต้นลงขั้นต่ำ ฿50,000 ผมจะช่วยเทรดให้เอง กำไรถอนได้ทันที เข้าบัญชีภายใน 24 ชม.!"',
        en: '"Welcome! Minimum deposit ฿50,000. I will trade for you. Profits can be withdrawn within 24 hours!"',
      },
      duration: 5000,
      edgeAnimation: { source: 'a1', target: 'a5', style: 'data_flow' },
    },
    {
      id: 'fi-06',
      order: 6,
      type: 'money_flow',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อโอน ฿100,000 เข้าแอป GlobalTrade (จริงๆ เข้าบัญชีมิจฉาชีพ)',
        en: '💸 Victim deposits ฿100,000 into GlobalTrade app (actually goes to scammer account)',
      },
      duration: 4000,
      moneyChange: -100000,
    },
    {
      id: 'fi-07',
      order: 7,
      type: 'action',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '📈 หน้าจอแอปแสดงกำไร ฿35,000! (ตัวเลขปลอม สร้างขึ้นมาเพื่อล่อให้ลงเพิ่ม)',
        en: '📈 App shows ฿35,000 profit! (Fake numbers designed to lure more investment)',
      },
      duration: 3500,
    },
    {
      id: 'fi-08',
      order: 8,
      type: 'dialogue',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '"เห็นไหมครับ กำไร 35% ภายใน 2 วัน! ถ้าเพิ่มเงินเป็น ฿500,000 ผมจะเปิดห้อง VIP ให้ กำไรเพิ่มอีก 3 เท่า!"',
        en: '"See? 35% profit in 2 days! If you deposit ฿500K, I will open VIP room for 3x more profits!"',
      },
      duration: 5000,
    },
    {
      id: 'fi-09',
      order: 9,
      type: 'money_flow',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อตื่นเต้น ลงเพิ่ม ฿400,000! รวมลงทุนไปแล้ว ฿500,000',
        en: '💸 Victim excitedly deposits ฿400,000 more! Total invested: ฿500,000',
      },
      duration: 4000,
      moneyChange: -400000,
    },
    {
      id: 'fi-10',
      order: 10,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 อันตราย! แอป "GlobalTrade Pro" ไม่ได้จดทะเบียนกับ กลต.! URL เป็น .cc ไม่ใช่ .com! กำไรในแอปเป็นตัวเลขปลอม!',
        en: '🚨 DANGER! "GlobalTrade Pro" is NOT registered with SEC! URL is .cc not .com! App profits are fake numbers!',
      },
      duration: 5000,
    },
    {
      id: 'fi-11',
      order: 11,
      type: 'action',
      agentId: 'a1',
      alignment: 'evil',
      content: {
        th: '🔒 เหยื่อลองถอนเงิน → "ต้องจ่ายค่าภาษี 20% ก่อน" → จ่ายแล้วก็ "มีค่าธรรมเนียมเพิ่ม" → ไม่มีวันได้เงินคืน!',
        en: '🔒 Victim tries to withdraw → "Must pay 20% tax first" → After paying: "Additional fees required" → Money never comes back!',
      },
      duration: 5000,
    },
    {
      id: 'fi-12',
      order: 12,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! แอป "GlobalTrade" เป็นแอปปลอม! ไม่มีการเทรดจริง ตัวเลขกำไรสร้างขึ้นมา เงินที่โอนไปเข้ากระเป๋ามิจฉาชีพโดยตรง!',
        en: '🔍 REVEALED! "GlobalTrade" is a fake app! No real trading. Profit numbers are fabricated. All money goes directly to scammers!',
      },
      duration: 5000,
    },
    {
      id: 'fi-13',
      order: 13,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 วิธีเช็ค: 1) ตรวจใบอนุญาตที่ กลต. (sec.or.th) 2) ถ้าต้อง "จ่ายภาษีก่อนถอน" = โกง 3) โฆษณาดาราแนะนำ 99% เป็นของปลอม 4) แอปจริงดาวน์โหลดจาก App Store/Play Store',
        en: '📚 Verify: 1) Check SEC license 2) "Pay tax before withdrawal" = scam 3) Celebrity ads are 99% fake 4) Real apps are on App Store/Play Store',
      },
      duration: 7000,
    },
    {
      id: 'fi-14',
      order: 14,
      type: 'education',
      agentId: 'a4',
      alignment: 'good',
      content: {
        th: '🛡️ กฎทอง: 1) ไม่มีการลงทุนใดการันตีกำไร 2) ผลตอบแทนสูง = ความเสี่ยงสูง 3) อย่าดาวน์โหลดแอปจากลิงก์ 4) แจ้ง กลต. หรือ 1599',
        en: '🛡️ Golden rules: 1) No investment guarantees profit 2) High returns = high risk 3) Never download apps from links 4) Report to SEC or 1599',
      },
      duration: 7000,
    },
  ],
  moneyLost: 500000,
  educationalPoints: [
    {
      th: 'แอปลงทุนจริงต้องมีใบอนุญาต กลต. เช็คได้ที่ sec.or.th',
      en: 'Real investment apps must have SEC license - check at sec.or.th',
    },
    {
      th: '"จ่ายภาษี/ค่าธรรมเนียมก่อนถอน" = กลโกง 100%',
      en: '"Pay tax/fee before withdrawal" = 100% scam',
    },
    {
      th: 'โฆษณาคนดังแนะนำลงทุน ส่วนใหญ่เป็น Deepfake หรือตัดต่อ',
      en: 'Celebrity investment endorsements are mostly deepfakes or edited',
    },
    {
      th: 'กำไรในแอปเป็นแค่ตัวเลข ไม่ใช่เงินจริง จนกว่าจะถอนได้',
      en: 'App profits are just numbers, not real money until withdrawn',
    },
  ],
  realWorldCases: [
    'แอปหุ้นปลอม "FBS Trader" หลอกคนไทยกว่า 5,000 ราย เสียหาย 1,500 ล้านบาท (2024)',
    'โฆษณา Deepfake "หมอช้าง" แนะนำ Crypto ปลอม เสียหาย 300 ล้านบาท (2023)',
    'เพจ Facebook "ลงทุนกับกูรู" หลอก 800 ราย เสียหาย 600 ล้านบาท (2024)',
  ],
};
