import { FraudScenario } from '../types';

export const jobScamScenario: FraudScenario = {
  id: 'job-scam-001',
  titleTh: 'หลอกสมัครงาน',
  titleEn: 'Job Scam',
  category: 'job_scam',
  difficulty: 'beginner',
  estimatedDuration: 100,
  description: {
    th: 'โฆษณารับสมัครงาน "นั่งทำที่บ้าน รายได้ 5,000/วัน" แต่ต้องจ่ายค่าสมัคร/ค่าอุปกรณ์ก่อน แล้วงานก็ไม่มี',
    en: 'Job ads promising "work from home, earn 5,000/day" but require upfront registration/equipment fees. The job never exists.',
  },
  involvedAgents: ['a0', 'a4', 'a2', 'a3'],
  evilAgents: ['a0', 'a4'],
  victimSetup: {
    defaultName: 'คุณนภา',
    defaultMoney: 100000,
    scenarioContext: {
      th: 'เพิ่งตกงานมา 2 เดือน กำลังหางานใหม่ เห็นโฆษณาใน Facebook "รับสมัครงาน Part-time ทำที่บ้าน รายได้ 3,000-5,000/วัน"',
      en: 'You\'ve been unemployed for 2 months. You see a Facebook ad: "Part-time work from home, earn 3,000-5,000/day"',
    },
  },
  steps: [
    {
      id: 'job-01',
      order: 1,
      type: 'action',
      agentId: 'a0',
      alignment: 'good',
      content: {
        th: '📱 โฆษณา Facebook: "รับสมัคร 50 อัตรา! ทำที่บ้าน รายได้ 3,000-5,000/วัน ไม่จำกัดวุฒิ แอด LINE: @jobhire2024"',
        en: '📱 Facebook ad: "50 positions available! Work from home, 3,000-5,000/day. No degree required. Add LINE: @jobhire2024"',
      },
      duration: 3000,
    },
    {
      id: 'job-02',
      order: 2,
      type: 'transformation',
      agentId: 'a0',
      alignment: 'transitioning',
      content: {
        th: '⚠️ ลุงสิงห์ กำลังแปลงร่างเป็น "HR บริษัทปลอม"...',
        en: '⚠️ Big Boss is transforming into "Fake company HR"...',
      },
      duration: 2500,
    },
    {
      id: 'job-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a0',
      alignment: 'evil',
      content: {
        th: '"สวัสดีค่ะ ยินดีต้อนรับสู่ Global Marketing Thai! งานของเราคือรีวิวสินค้าออนไลน์ ได้ค่าจ้าง 200-500 บาท/รีวิว เริ่มงานได้เลยวันนี้!"',
        en: '"Welcome to Global Marketing Thai! Your job is reviewing products online. Earn 200-500 per review. Start today!"',
      },
      duration: 5000,
    },
    {
      id: 'job-04',
      order: 4,
      type: 'transformation',
      agentId: 'a4',
      alignment: 'transitioning',
      content: {
        th: '⚠️ ครูหมี กำลังแปลงร่างเป็น "อ.หมีโต้ง — คอยกดดันให้จ่ายเงิน"...',
        en: '⚠️ Scam Trainer is transforming into "Team leader" who pressures payment...',
      },
      duration: 2500,
    },
    {
      id: 'job-05',
      order: 5,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"แต่ก่อนเริ่มงาน ต้องจ่ายค่าลงทะเบียน ฿2,900 และค่าชุดอุปกรณ์ ฿5,000 รวม ฿7,900 ค่ะ ได้คืนภายใน 3 วันทำงานแรก!"',
        en: '"Before starting, you need to pay registration fee ฿2,900 and equipment kit ฿5,000. Total ฿7,900. You\'ll earn it back in 3 days!"',
      },
      duration: 5000,
      edgeAnimation: { source: 'a4', target: 'a0', style: 'data_flow' },
    },
    {
      id: 'job-06',
      order: 6,
      type: 'money_flow',
      agentId: 'a0',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อจ่ายค่าลงทะเบียน + อุปกรณ์ ฿7,900',
        en: '💸 Victim pays registration + equipment ฿7,900',
      },
      duration: 3000,
      moneyChange: -7900,
    },
    {
      id: 'job-07',
      order: 7,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"เยี่ยมค่ะ! ตอนนี้ต้อง \"ปั๊มยอด\" ก่อน คือสั่งซื้อสินค้าในระบบ แล้วจะได้ค่าจ้าง+เงินคืน ครั้งแรกสั่ง ฿15,000 ค่ะ"',
        en: '"Great! Now you need to \'boost orders\' first. Buy products in the system, then get commission + refund. First order: ฿15,000"',
      },
      duration: 6000,
    },
    {
      id: 'job-08',
      order: 8,
      type: 'money_flow',
      agentId: 'a0',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อ "สั่งซื้อ" สินค้าปลอม ฿15,000 (ไม่มีสินค้าจริง)',
        en: '💸 Victim "orders" fake products ฿15,000 (no real products)',
      },
      duration: 3500,
      moneyChange: -15000,
    },
    {
      id: 'job-09',
      order: 9,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"เกิดข้อผิดพลาดค่ะ ต้องสั่งเพิ่มอีก ฿30,000 ถึงจะปลดล็อคเงินทั้งหมดได้ ถ้าไม่ทำ เงินก่อนหน้าจะหายหมดเลยนะคะ!"',
        en: '"Error occurred! Need to order ฿30,000 more to unlock all funds. If you don\'t, all previous money will be lost!"',
      },
      duration: 5000,
    },
    {
      id: 'job-10',
      order: 10,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 หยุด! นี่คือกลโกง "หลอกสมัครงาน"! งานจริงไม่เคยเก็บค่าสมัคร และ "ปั๊มยอด" คือวิธีดูดเงินเพิ่ม!',
        en: '🚨 STOP! This is a "Job Scam"! Real jobs NEVER charge registration fees, and "order boosting" is a money drain tactic!',
      },
      duration: 5000,
    },
    {
      id: 'job-11',
      order: 11,
      type: 'money_flow',
      agentId: 'a0',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อจ่ายเพิ่มอีก ฿30,000 เพราะกลัวเสียเงินก่อนหน้า... รวมเสียไป ฿52,900!',
        en: '💸 Victim pays ฿30,000 more fearing loss of previous money... Total lost: ฿52,900!',
      },
      duration: 3500,
      moneyChange: -30000,
    },
    {
      id: 'job-12',
      order: 12,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! "Global Marketing Thai" ไม่มีจริง! ไม่มีสินค้า ไม่มีงาน ทั้งหมดคือกลโกงหลอกให้จ่ายเงินซ้ำแล้วซ้ำเล่า!',
        en: '🔍 REVEALED! "Global Marketing Thai" doesn\'t exist! No products, no job. It\'s a scam that makes you pay repeatedly!',
      },
      duration: 5000,
    },
    {
      id: 'job-13',
      order: 13,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 สัญญาณเตือน: 1) ต้องจ่ายเงินก่อนเริ่มงาน 2) รายได้สูงเกินจริง 3) "ปั๊มยอด/สั่งซื้อ" = โกง 4) กดดันให้จ่ายเพิ่มเรื่อยๆ 5) บริษัทหาข้อมูลไม่เจอ',
        en: '📚 Warning signs: 1) Pay before starting 2) Unrealistic income 3) "Order boosting" = scam 4) Pressure to pay more 5) Company can\'t be found online',
      },
      duration: 7000,
    },
    {
      id: 'job-14',
      order: 14,
      type: 'education',
      agentId: 'a3',
      alignment: 'good',
      content: {
        th: '🛡️ ป้องกัน: 1) งานจริงไม่เก็บค่าสมัคร 2) เช็คบริษัทที่ DBD (dbd.go.th) 3) อย่าโอนเงิน "ปั๊มยอด" 4) สมัครงานผ่านเว็บจริง เช่น JobThai, LinkedIn 5) แจ้ง 1599',
        en: '🛡️ Prevention: 1) Real jobs don\'t charge 2) Check company at DBD 3) Never pay for "order boosting" 4) Use real job sites 5) Report to 1599',
      },
      duration: 7000,
    },
  ],
  moneyLost: 52900,
  educationalPoints: [
    {
      th: 'งานจริงไม่เคยเก็บค่าสมัครหรือค่าอุปกรณ์',
      en: 'Real jobs never charge registration or equipment fees',
    },
    {
      th: '"ปั๊มยอด/สั่งซื้อสินค้า" = กลโกงดูดเงิน 100%',
      en: '"Order boosting/purchasing" = money drain scam 100%',
    },
    {
      th: 'รายได้ 3,000-5,000/วัน ทำที่บ้าน = เกินจริงแน่นอน',
      en: '3,000-5,000/day work from home = definitely too good to be true',
    },
    {
      th: 'เช็คบริษัทที่ กรมพัฒนาธุรกิจ (dbd.go.th) ก่อนเสมอ',
      en: 'Always check company at Department of Business Development (dbd.go.th)',
    },
  ],
  realWorldCases: [
    'นักศึกษาจบใหม่ถูกหลอก "รีวิวสินค้า" เสีย 180,000 บาท ใน 1 สัปดาห์ (2024)',
    'แม่บ้านถูกหลอก "ปั๊มยอด Shopee ปลอม" เสียเงิน 350,000 บาท (2023)',
    'ผู้สูงอายุถูกหลอกสมัครงาน "พิมพ์ข้อมูล" จ่ายค่าสมัคร 5 รอบ เสียรวม 95,000 บาท (2024)',
  ],
};
