import { FraudScenario } from '../types';

export const loanAppScenario: FraudScenario = {
  id: 'loan-app-001',
  titleTh: 'แอปเงินกู้นอกระบบ',
  titleEn: 'Illegal Loan App',
  category: 'loan_app',
  difficulty: 'intermediate',
  estimatedDuration: 110,
  description: {
    th: 'กู้เงินผ่านแอปเงินกู้ ดอกเบี้ยถูก อนุมัติเร็ว แต่ถูกเรียกเก็บค่าธรรมเนียมซ้ำๆ จ่ายดอกเบี้ยโหด และถูกข่มขู่ทวงหนี้',
    en: 'Borrow money via loan app with low interest and fast approval, but get hit with hidden fees, predatory interest, and threatening debt collection.',
  },
  involvedAgents: ['a3', 'a5', 'a2', 'a1'],
  evilAgents: ['a3', 'a5'],
  victimSetup: {
    defaultName: 'คุณสมศักดิ์',
    defaultMoney: 80000,
    scenarioContext: {
      th: 'เงินเดือนออกอีก 2 สัปดาห์ แต่มีค่าเทอมลูกต้องจ่ายพรุ่งนี้ เห็นโฆษณา "กู้ด่วน อนุมัติ 5 นาที ดอกเบี้ยต่ำ"...',
      en: 'Payday is 2 weeks away but school tuition is due tomorrow. You see an ad: "Quick loan, approved in 5 minutes, low interest"...',
    },
  },
  steps: [
    {
      id: 'loan-01',
      order: 1,
      type: 'action',
      agentId: 'a3',
      alignment: 'good',
      content: {
        th: '📱 โฆษณา: "EasyLoan กู้ได้ 5,000-50,000 อนุมัติใน 5 นาที ดอกเบี้ย 0.5%/วัน ไม่ต้องค้ำ ดาวน์โหลดเลย!"',
        en: '📱 Ad: "EasyLoan borrow 5,000-50,000, approved in 5 min, 0.5%/day interest, no collateral!"',
      },
      duration: 3000,
    },
    {
      id: 'loan-02',
      order: 2,
      type: 'transformation',
      agentId: 'a3',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Guardian Angel กำลังแปลงร่างเป็น "น้องพลอย — แอดมินแอปเงินกู้เถื่อน"...',
        en: '⚠️ Guardian Angel is transforming into illegal loan app admin...',
      },
      duration: 2500,
    },
    {
      id: 'loan-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '"สวัสดีค่ะ ยินดีต้อนรับสู่ EasyLoan! กรุณากรอกข้อมูล: ชื่อ, เลขบัตรประชาชน, เบอร์โทร, และรูปบัตรประชาชนค่ะ"',
        en: '"Welcome to EasyLoan! Please fill in: name, ID card number, phone number, and photo of your ID card."',
      },
      duration: 5000,
    },
    {
      id: 'loan-04',
      order: 4,
      type: 'action',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '🔓 แอปขอสิทธิ์เข้าถึง: รายชื่อผู้ติดต่อ, รูปภาพ, SMS, ตำแหน่ง GPS ทั้งหมด! (เพื่อใช้ข่มขู่ทีหลัง)',
        en: '🔓 App requests access to: contacts, photos, SMS, GPS location! (To use as leverage for threats later)',
      },
      duration: 4000,
    },
    {
      id: 'loan-05',
      order: 5,
      type: 'transformation',
      agentId: 'a5',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Money Guard กำลังแปลงร่างเป็น "คุณสมคิด — หัวหน้าทีมทวงหนี้"...',
        en: '⚠️ Money Guard is transforming into debt collection team leader...',
      },
      duration: 2500,
    },
    {
      id: 'loan-06',
      order: 6,
      type: 'dialogue',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '"อนุมัติแล้วค่ะ! กู้ ฿20,000 แต่หักค่าธรรมเนียม ฿4,000 ค่าประกัน ฿2,000 ได้รับจริง ฿14,000 ดอกเบี้ย 0.5%/วัน (= 182%/ปี!)"',
        en: '"Approved! Borrow ฿20,000 minus ฿4,000 fee and ฿2,000 insurance. Actual amount: ฿14,000. Interest 0.5%/day (= 182%/year!)"',
      },
      duration: 6000,
      edgeAnimation: { source: 'a3', target: 'a5', style: 'data_flow' },
    },
    {
      id: 'loan-07',
      order: 7,
      type: 'money_flow',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '💸 ได้เงินจริงแค่ ฿14,000 แต่ต้องคืน ฿20,000 + ดอกเบี้ย → สูญเสีย ฿6,000 ทันที!',
        en: '💸 Only receive ฿14,000 but must repay ฿20,000 + interest → Lose ฿6,000 immediately!',
      },
      duration: 4000,
      moneyChange: -6000,
    },
    {
      id: 'loan-08',
      order: 8,
      type: 'dialogue',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '"คุณค้างชำระ 3 วัน ดอกเบี้ยเพิ่มเป็น 2%/วัน! ถ้าไม่จ่ายวันนี้ จะส่งข้อความทวงหนี้ไปหาทุกคนในมือถือคุณ! รูปบัตรประชาชนก็อยู่กับเรา!"',
        en: '"You are 3 days late! Interest now 2%/day! If you don\'t pay today, we will message everyone in your contacts! We have your ID card photo!"',
      },
      duration: 6000,
    },
    {
      id: 'loan-09',
      order: 9,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 นี่คือ "แอปเงินกู้เถื่อน"! ดอกเบี้ย 0.5-2%/วัน = ผิดกฎหมาย! ดอกเบี้ยถูกกฎหมายสูงสุด 15%/ปี! แอปเหล่านี้ใช้ข้อมูลส่วนตัวข่มขู่เหยื่อ!',
        en: '🚨 This is an ILLEGAL LOAN APP! 0.5-2%/day interest is illegal! Legal max is 15%/year! These apps use personal data to threaten victims!',
      },
      duration: 5000,
    },
    {
      id: 'loan-10',
      order: 10,
      type: 'money_flow',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '💸 จ่ายดอกเบี้ย + ค่าต่อสัญญา ฿12,000 แต่ยอดหนี้ไม่ลดเลย! ยังค้าง ฿20,000 เหมือนเดิม!',
        en: '💸 Pay interest + renewal fee ฿12,000 but debt doesn\'t decrease! Still owe ฿20,000!',
      },
      duration: 4000,
      moneyChange: -12000,
    },
    {
      id: 'loan-11',
      order: 11,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! "EasyLoan" คือแอปเงินกู้นอกระบบ! หักค่าธรรมเนียมล่วงหน้า คิดดอกเบี้ยโหด และใช้ข้อมูลส่วนตัวข่มขู่!',
        en: '🔍 REVEALED! "EasyLoan" is an illegal loan app! Deducts upfront fees, charges predatory interest, and uses personal data as leverage!',
      },
      duration: 5000,
    },
    {
      id: 'loan-12',
      order: 12,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 สัญญาณเตือน: 1) หักค่าธรรมเนียมจากยอดกู้ 2) ดอกเบี้ยเกิน 15%/ปี = ผิดกฎหมาย 3) ขอเข้าถึงรายชื่อผู้ติดต่อ/รูปภาพ 4) ข่มขู่ทวงหนี้ = แจ้งตำรวจได้',
        en: '📚 Warning signs: 1) Fees deducted from loan 2) Interest over 15%/year = illegal 3) Requests contact/photo access 4) Threatening collection = report to police',
      },
      duration: 7000,
    },
    {
      id: 'loan-13',
      order: 13,
      type: 'education',
      agentId: 'a1',
      alignment: 'good',
      content: {
        th: '🛡️ ทางออก: 1) หยุดจ่ายทันที (หนี้นอกระบบฟ้องไม่ได้) 2) แจ้งตำรวจ/1599 3) ลบแอป เปลี่ยนรหัส 4) กู้ในระบบ: ธนาคาร, สหกรณ์, ธ.ก.ส. 5) ปรึกษาสายด่วน ศคช. 1213',
        en: '🛡️ Way out: 1) Stop paying (illegal debt is unenforceable) 2) Report to police/1599 3) Delete app, change passwords 4) Borrow legally: banks, cooperatives 5) Consult hotline 1213',
      },
      duration: 7000,
    },
  ],
  moneyLost: 18000,
  educationalPoints: [
    {
      th: 'ดอกเบี้ยเกิน 15%/ปี (0.04%/วัน) = ผิดกฎหมาย',
      en: 'Interest over 15%/year (0.04%/day) is illegal in Thailand',
    },
    {
      th: 'แอปที่ขอเข้าถึงรายชื่อ/รูปภาพ = จะใช้ข่มขู่ทีหลัง',
      en: 'Apps requesting contacts/photos access will use them for threats',
    },
    {
      th: 'หนี้นอกระบบฟ้องศาลไม่ได้ หยุดจ่ายแล้วแจ้งตำรวจ',
      en: 'Illegal debt cannot be enforced in court. Stop paying and report to police.',
    },
    {
      th: 'กู้ในระบบได้ที่: ธนาคาร, สหกรณ์, ธ.ก.ส., ออมสิน',
      en: 'Legal borrowing: banks, cooperatives, BAAC, Government Savings Bank',
    },
  ],
  realWorldCases: [
    'แอปเงินกู้จีน 500+ แอป ถูกปิด เหยื่อรวมกว่า 100,000 ราย (2023)',
    'สาวโรงงาน กู้ ฿5,000 → ถูกทวง ฿50,000 ภายใน 2 เดือน (2024)',
    'ครอบครัวถูกข่มขู่ ส่งข้อความทวงหนี้ไปหาทุกคนในเบอร์โทร (2024)',
  ],
};
