import { FraudScenario } from '../types';

export const ponziSchemeScenario: FraudScenario = {
  id: 'ponzi-scheme-001',
  titleTh: 'แชร์ลูกโซ่',
  titleEn: 'Ponzi Scheme',
  category: 'ponzi_scheme',
  difficulty: 'intermediate',
  estimatedDuration: 130,
  description: {
    th: 'เพื่อนชวนลงทุน การันตีผลตอบแทน 10% ต่อเดือน ได้เงินจริงรอบแรก พอเพิ่มเงินลงทุน เว็บหายไปเลย',
    en: 'A friend invites you to invest with guaranteed 10% monthly returns. First payout is real, but when you invest more, the platform vanishes.',
  },
  involvedAgents: ['a4', 'a5', 'a2', 'a3'],
  evilAgents: ['a4', 'a5'],
  victimSetup: {
    defaultName: 'คุณประยุทธ์',
    defaultMoney: 500000,
    scenarioContext: {
      th: 'เพื่อนสนิทส่งลิงก์มาใน LINE กลุ่ม บอกว่าลงทุนแล้วได้เงินจริง มีหลักฐานการถอนเงินให้ดู...',
      en: 'A close friend shares an investment link in your LINE group, showing proof of actual withdrawals...',
    },
  },
  steps: [
    {
      id: 'pz-01',
      order: 1,
      type: 'action',
      agentId: 'a4',
      alignment: 'good',
      content: {
        th: '💬 ข้อความใน LINE กลุ่ม: "ลงทุนกับ TrustCoin ได้จริงนะ! ผมถอนมาแล้ว 50,000 ดูสลิปนี่เลย!"',
        en: '💬 LINE group message: "TrustCoin investment is real! I just withdrew 50,000, look at my slip!"',
      },
      duration: 3500,
    },
    {
      id: 'pz-02',
      order: 2,
      type: 'transformation',
      agentId: 'a4',
      alignment: 'transitioning',
      content: {
        th: '⚠️ ครูหมี กำลังแปลงร่างเป็น "อ.หมีโต้ง — ดึงคนเข้าแชร์"...',
        en: '⚠️ Scam Trainer is transforming into "Investment Guru recruiter"...',
      },
      duration: 2500,
    },
    {
      id: 'pz-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"TrustCoin ใช้ AI เทรดอัตโนมัติ การันตีผลตอบแทน 10% ต่อเดือน! ลง 100,000 ได้คืน 110,000 ทุกเดือน มีใบอนุญาต กลต. (ปลอม)"',
        en: '"TrustCoin uses AI auto-trading. Guaranteed 10% monthly returns! Invest 100K, get 110K monthly. SEC licensed (fake)."',
      },
      duration: 6000,
    },
    {
      id: 'pz-04',
      order: 4,
      type: 'money_flow',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อลองลง ฿50,000 เพื่อทดสอบ... → ได้เงินคืน ฿55,000 จริง! (เงินจากเหยื่อคนใหม่)',
        en: '💸 Victim tests with ฿50,000... → Actually receives ฿55,000 back! (Paid with new victim money)',
      },
      duration: 4000,
      moneyChange: -50000,
    },
    {
      id: 'pz-05',
      order: 5,
      type: 'transformation',
      agentId: 'a5',
      alignment: 'transitioning',
      content: {
        th: '⚠️ จ.ส.ต.จิ้งจอก กำลังแปลงร่างเป็น "ผจก.สมคิด — ผู้จัดการกองทุนปลอม"...',
        en: '⚠️ Money Guard is transforming into fake fund manager...',
      },
      duration: 2500,
    },
    {
      id: 'pz-06',
      order: 6,
      type: 'dialogue',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '"ยินดีต้อนรับสู่ TrustCoin VIP! ตอนนี้มีโปรพิเศษ ลง ฿200,000 ขึ้นไป ได้ผลตอบแทน 15% ต่อเดือน! จำกัดเวลา 24 ชม.!"',
        en: '"Welcome to TrustCoin VIP! Special promo: invest ฿200K+ for 15% monthly returns! Limited 24 hours!"',
      },
      duration: 5000,
      edgeAnimation: { source: 'a5', target: 'a4', style: 'data_flow' },
    },
    {
      id: 'pz-07',
      order: 7,
      type: 'money_flow',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อมั่นใจ (เพราะได้เงินจริงรอบแรก) → ลงเพิ่ม ฿200,000!',
        en: '💸 Victim is confident (got real money first time) → Invests ฿200,000 more!',
      },
      duration: 4000,
      moneyChange: -200000,
    },
    {
      id: 'pz-08',
      order: 8,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"ชวนเพื่อนมาลงด้วย ได้ค่าแนะนำ 5%! ยิ่งชวนมาก ยิ่งได้มาก! สร้างทีมลงทุน passive income!"',
        en: '"Refer friends for 5% commission! The more you recruit, the more you earn! Build your passive income team!"',
      },
      duration: 5000,
    },
    {
      id: 'pz-09',
      order: 9,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 อันตราย! ผลตอบแทน "การันตี 10-15% ต่อเดือน" = แชร์ลูกโซ่! ไม่มีการลงทุนจริงที่ให้ผลตอบแทนสูงขนาดนี้!',
        en: '🚨 DANGER! "Guaranteed 10-15% monthly" = Ponzi scheme! No real investment gives these returns!',
      },
      duration: 5000,
    },
    {
      id: 'pz-10',
      order: 10,
      type: 'action',
      agentId: 'a5',
      alignment: 'evil',
      content: {
        th: '🔒 วันรุ่งขึ้น... เว็บ TrustCoin เข้าไม่ได้! ถอนเงินไม่ได้! LINE กลุ่มถูกลบ! ผู้จัดการหายตัวไป!',
        en: '🔒 Next day... TrustCoin website is down! Cannot withdraw! LINE group deleted! Manager vanished!',
      },
      duration: 4000,
    },
    {
      id: 'pz-11',
      order: 11,
      type: 'money_flow',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '💸 เงินที่ลงทุนไป ฿200,000 หายทั้งหมด (ได้คืนแค่ ฿5,000 จากรอบแรก) → สูญสุทธิ ฿245,000!',
        en: '💸 All ฿200,000 investment gone (only ฿5,000 returned in first round) → Net loss ฿245,000!',
      },
      duration: 4000,
      moneyChange: -45000,
    },
    {
      id: 'pz-12',
      order: 12,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! "TrustCoin" คือแชร์ลูกโซ่! ไม่มีการเทรดจริง เงินที่ได้รอบแรกคือเงินจากเหยื่อรายใหม่ พอไม่มีเหยื่อเพิ่ม ระบบก็ล่ม!',
        en: '🔍 REVEALED! TrustCoin was a Ponzi scheme! No real trading. First payouts came from new victims. When recruiting stops, it collapses!',
      },
      duration: 5000,
    },
    {
      id: 'pz-13',
      order: 13,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 วิธีสังเกตแชร์ลูกโซ่: 1) "การันตีผลตอบแทน" สูงผิดปกติ 2) ให้ชวนคนใหม่มาลง → ค่าแนะนำ 3) ไม่มีผลิตภัณฑ์จริง 4) ไม่มีใบอนุญาต กลต. จริง (เช็คได้ที่ sec.or.th)',
        en: '📚 Ponzi red flags: 1) Abnormally high "guaranteed" returns 2) Recruitment rewards 3) No real product 4) Check SEC license at sec.or.th',
      },
      duration: 7000,
    },
    {
      id: 'pz-14',
      order: 14,
      type: 'education',
      agentId: 'a3',
      alignment: 'good',
      content: {
        th: '🛡️ ป้องกัน: 1) ผลตอบแทนเกิน 2% ต่อเดือน → สงสัยไว้ก่อน 2) เช็คใบอนุญาตที่ กลต. sec.or.th 3) "การันตีกำไร" = โกง 100% 4) แจ้ง DSI หรือ 1599',
        en: '🛡️ Prevention: 1) Returns over 2% monthly → be suspicious 2) Check SEC at sec.or.th 3) "Guaranteed profit" = 100% scam 4) Report to DSI or 1599',
      },
      duration: 7000,
    },
  ],
  moneyLost: 295000,
  educationalPoints: [
    {
      th: '"การันตีผลตอบแทน" สูงผิดปกติ = แชร์ลูกโซ่ 100%',
      en: '"Guaranteed high returns" = 100% Ponzi scheme',
    },
    {
      th: 'ได้เงินจริงรอบแรก ไม่ได้แปลว่าจริง — เป็นเงินจากเหยื่อรายใหม่',
      en: 'First real payout does not mean it\'s legit — it\'s new victim money',
    },
    {
      th: 'ถ้ามีค่าแนะนำ/ชวนเพื่อน = โครงสร้างแชร์ลูกโซ่',
      en: 'Recruitment commissions = Ponzi structure',
    },
    {
      th: 'ตรวจใบอนุญาตที่ กลต. (sec.or.th) ก่อนลงทุนเสมอ',
      en: 'Always verify licenses at SEC (sec.or.th) before investing',
    },
  ],
  realWorldCases: [
    'Forex-3D หลอกคนไทย 2,000+ ราย เสียหาย 2,400 ล้านบาท (2020)',
    'แชร์ลูกโซ่ "ตลาดนัดออนไลน์" เสียหาย 800 ล้านบาท ผู้เสียหาย 10,000+ ราย (2023)',
    'แอป Bitkub ปลอม หลอกลงทุน Bitcoin ได้ผลตอบแทน 30%/เดือน เสียหาย 500 ล้านบาท (2024)',
  ],
};
