import { FraudScenario } from '../types';

export const romanceScamScenario: FraudScenario = {
  id: 'romance-scam-001',
  titleTh: 'แก๊งหลอกรัก (Romance Scam)',
  titleEn: 'Romance Scam',
  category: 'romance_scam',
  difficulty: 'intermediate',
  estimatedDuration: 150,
  description: {
    th: 'คนแปลกหน้าทักมาใน Facebook/LINE หน้าตาดี พูดจาดี สร้างความสัมพันธ์ แล้วค่อยๆ ขอเงินไปเรื่อยๆ',
    en: 'A stranger contacts you on social media, builds a romantic relationship over weeks, then gradually asks for money for various emergencies.',
  },
  involvedAgents: ['a3', 'a4', 'a2', 'a0'],
  evilAgents: ['a3', 'a4'],
  victimSetup: {
    defaultName: 'คุณวิภา',
    defaultMoney: 1000000,
    scenarioContext: {
      th: 'มีคนทักมาใน Facebook ชื่อ "ดร.ไมเคิล" รูปโปรไฟล์เป็นฝรั่งหล่อ บอกว่าเป็นหมอทำงานอยู่อเมริกา...',
      en: 'A man named "Dr. Michael" messaged you on Facebook. His profile shows a handsome Western doctor working in the US...',
    },
  },
  steps: [
    {
      id: 'rom-01',
      order: 1,
      type: 'action',
      agentId: 'a3',
      alignment: 'good',
      content: {
        th: '📲 มีข้อความจาก "ดร.ไมเคิล" ใน Facebook Messenger: "สวัสดีครับ เห็นโปรไฟล์คุณน่าสนใจมาก"',
        en: '📲 Message from "Dr. Michael" on Facebook: "Hi, your profile looks very interesting"',
      },
      duration: 3000,
    },
    {
      id: 'rom-02',
      order: 2,
      type: 'transformation',
      agentId: 'a3',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Guardian Angel กำลังแปลงร่างเป็น "น้องพลอย — ผู้จัดการแชทของแก๊ง"...',
        en: '⚠️ Guardian Angel is transforming into the scam gang chat manager...',
      },
      duration: 2500,
    },
    {
      id: 'rom-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '"คุณเป็นคนพิเศษมาก ผมไม่เคยรู้สึกแบบนี้กับใคร ผมอยากมาหาคุณที่เมืองไทย แต่ตอนนี้ผมมีปัญหา..."',
        en: '"You are very special. I have never felt this way about anyone. I want to visit you in Thailand, but I have a problem..."',
      },
      duration: 5000,
    },
    {
      id: 'rom-04',
      order: 4,
      type: 'transformation',
      agentId: 'a4',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Scam Trainer กำลังแปลงร่างเป็น "กูรูความรัก — ผู้ช่วยของ ดร.ไมเคิล"...',
        en: '⚠️ Scam Trainer is transforming into "Dr. Michael\'s assistant"...',
      },
      duration: 2500,
    },
    {
      id: 'rom-05',
      order: 5,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: 'สวัสดีค่ะ ดิฉันเป็นผู้ช่วยของ ดร.ไมเคิล เรื่องนี้ต้องเร่งด่วน คุณหมอถูกกักตัวที่สนามบิน เพราะมีภาษีศุลกากรค้าง ต้องจ่าย ฿150,000 ก่อนถึงจะปล่อยตัว',
        en: 'Hello, I am Dr. Michael\'s assistant. He is detained at the airport due to customs tax. He needs ฿150,000 to be released.',
      },
      duration: 6000,
      edgeAnimation: { source: 'a4', target: 'a3', style: 'data_flow' },
    },
    {
      id: 'rom-06',
      order: 6,
      type: 'money_flow',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อโอนเงิน ฿150,000 เพื่อ "ช่วยคนรัก" ไปบัญชีที่ระบุ...',
        en: '💸 Victim transfers ฿150,000 to "help loved one"...',
      },
      duration: 4000,
      moneyChange: -150000,
      edgeAnimation: { source: 'a0', target: 'a3', style: 'money_flow' },
    },
    {
      id: 'rom-07',
      order: 7,
      type: 'dialogue',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '"ขอบคุณมากที่รักค่ะ แต่ตอนนี้เจอปัญหาอีก ต้องจ่ายค่ารักษาพยาบาลด่วน ฿200,000 หมอเป็นลม... ช่วยหน่อยได้ไหม?"',
        en: '"Thank you my love, but now there\'s another problem. Medical emergency ฿200,000. Doctor collapsed... Can you help?"',
      },
      duration: 5000,
    },
    {
      id: 'rom-08',
      order: 8,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 ระวัง! รูปแบบนี้คือ Romance Scam! ลักษณะ: ทักมาเอง, สร้างความรัก, ขอเงินครั้งแล้วครั้งเล่า, ไม่เคยเจอตัวจริง!',
        en: '🚨 Warning! This is a classic Romance Scam! Signs: unsolicited contact, love-bombing, repeated money requests, never meet in person!',
      },
      duration: 5000,
    },
    {
      id: 'rom-09',
      order: 9,
      type: 'money_flow',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อโอนอีก ฿200,000 ด้วยความเป็นห่วง... รวมเสียไปแล้ว ฿350,000',
        en: '💸 Victim transfers another ฿200,000 out of concern... Total lost: ฿350,000',
      },
      duration: 4000,
      moneyChange: -200000,
    },
    {
      id: 'rom-10',
      order: 10,
      type: 'dialogue',
      agentId: 'a4',
      alignment: 'evil',
      content: {
        th: '"ดร.ไมเคิล ต้องส่งกล่องพัสดุมีทองคำมาให้คุณ แต่ถูกกักที่ศุลกากร ต้องจ่ายค่าปล่อยของ ฿350,000"',
        en: '"Dr. Michael needs to send you a box of gold. It is held at customs. Need ฿350,000 to release it."',
      },
      duration: 5000,
    },
    {
      id: 'rom-11',
      order: 11,
      type: 'money_flow',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '💸 เหยื่อโอนอีก ฿350,000 หวังจะได้ทองคำตอบแทน... รวมเสียไป ฿700,000!',
        en: '💸 Victim transfers another ฿350,000 hoping to receive gold... Total lost: ฿700,000!',
      },
      duration: 4000,
      moneyChange: -350000,
    },
    {
      id: 'rom-12',
      order: 12,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! "ดร.ไมเคิล" ไม่มีตัวตน! รูปโปรไฟล์ขโมยมาจากอินเทอร์เน็ต แชทโดยแก๊งมิจฉาชีพในต่างประเทศ ทั้งหมดเป็นบทละคร!',
        en: '🔍 REVEALED! "Dr. Michael" does not exist! Profile photos were stolen. Messages were sent by a scam gang. It was all scripted!',
      },
      duration: 5000,
    },
    {
      id: 'rom-13',
      order: 13,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 สัญญาณเตือน Romance Scam: 1) ไม่เคยเจอตัวจริง หรือวิดีโอคอลมัวๆ 2) ขอเงินซ้ำๆ โดยมีเหตุผลใหม่เสมอ 3) สร้างความรักเร็วผิดปกติ 4) ห้ามบอกคนรอบข้าง',
        en: '📚 Romance Scam red flags: 1) Never meet in person 2) Repeated money requests with new reasons 3) Love-bombing 4) Isolating from friends/family',
      },
      duration: 7000,
    },
    {
      id: 'rom-14',
      order: 14,
      type: 'education',
      agentId: 'a0',
      alignment: 'good',
      content: {
        th: '🛡️ วิธีป้องกัน: 1) ค้นรูปใน Google Images ดูว่าเป็นรูปขโมยไหม 2) อย่าโอนเงินให้คนที่ไม่เคยเจอตัว 3) ปรึกษาคนใกล้ชิดก่อนตัดสินใจ 4) แจ้ง 1599',
        en: '🛡️ Prevention: 1) Reverse image search on Google 2) Never send money to someone you haven\'t met 3) Consult family first 4) Report to 1599',
      },
      duration: 7000,
    },
  ],
  moneyLost: 700000,
  educationalPoints: [
    {
      th: 'อย่าโอนเงินให้คนที่ไม่เคยเจอตัวจริง ไม่ว่าจะรู้สึกรักแค่ไหน',
      en: 'Never send money to someone you have never met in person',
    },
    {
      th: 'ค้นรูปด้วย Google Images — Romance Scam ใช้รูปขโมยจากคนอื่น',
      en: 'Reverse search photos — Romance scammers use stolen photos',
    },
    {
      th: 'ถ้าขอเงินหลายรอบ โดยมีเหตุผลใหม่ทุกครั้ง = โกง 100%',
      en: 'Multiple money requests with different excuses = 100% scam',
    },
    {
      th: 'มิจฉาชีพมักห้ามบอกคนรอบข้าง เพราะกลัวถูกจับได้',
      en: 'Scammers isolate victims from friends and family',
    },
  ],
  realWorldCases: [
    'หญิงไทย วัย 55 ปี เสียเงิน 12 ล้านบาท ให้ "ทหารอเมริกัน" ที่ไม่มีตัวตน (2024)',
    'ข้าราชการเกษียณ ถูกหลอก 3 ล้านบาท จาก "นักธุรกิจอังกฤษ" ใน LINE (2023)',
    'สาวออฟฟิศ สูญ 800,000 บาท ให้ "หมอ" ที่ขอค่ารักษาฉุกเฉิน 5 รอบ (2024)',
  ],
};
