import { FraudScenario } from '../types';

export const smsPhishingScenario: FraudScenario = {
  id: 'sms-phishing-001',
  titleTh: 'SMS ลิงก์ปลอม',
  titleEn: 'SMS Phishing Link',
  category: 'sms_phishing',
  difficulty: 'beginner',
  estimatedDuration: 90,
  description: {
    th: 'ได้รับ SMS แจ้งว่ามีพัสดุค้างส่ง ต้องกดลิงก์จ่ายค่าจัดส่ง แต่จริงๆ เป็นเว็บปลอมดูดข้อมูลบัตรเครดิต',
    en: 'You receive an SMS about an undelivered package. The link leads to a fake payment page that steals your credit card information.',
  },
  involvedAgents: ['a6', 'a3', 'a2', 'a1'],
  evilAgents: ['a6', 'a3'],
  victimSetup: {
    defaultName: 'คุณสมหญิง',
    defaultMoney: 50000,
    scenarioContext: {
      th: 'คุณเพิ่งสั่งของออนไลน์ไปเมื่อวาน กำลังรอพัสดุอยู่ แล้วก็ได้รับ SMS...',
      en: 'You just ordered something online yesterday and are waiting for delivery when you receive an SMS...',
    },
  },
  steps: [
    {
      id: 'sms-01',
      order: 1,
      type: 'action',
      agentId: 'a6',
      alignment: 'good',
      content: {
        th: '📱 มี SMS เข้ามา 1 ข้อความ จากหมายเลข +66-8X-XXX-XXXX',
        en: '📱 New SMS from +66-8X-XXX-XXXX',
      },
      duration: 2500,
    },
    {
      id: 'sms-02',
      order: 2,
      type: 'transformation',
      agentId: 'a6',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Lightning Alert กำลังแปลงร่างเป็น "SMS Bot ส่งลิงก์ปลอม"...',
        en: '⚠️ Lightning Alert is transforming into "Phishing SMS Bot"...',
      },
      duration: 2500,
    },
    {
      id: 'sms-03',
      order: 3,
      type: 'dialogue',
      agentId: 'a6',
      alignment: 'evil',
      content: {
        th: '[Kerry Express] พัสดุของท่านค้างส่ง กรุณาชำระค่าจัดส่งเพิ่ม 35 บาท ภายใน 24 ชม. คลิก: https://kerry-th.pay-confirm.cc/track',
        en: '[Kerry Express] Your package is held. Please pay additional 35 THB shipping within 24h. Click: https://kerry-th.pay-confirm.cc/track',
      },
      duration: 5000,
    },
    {
      id: 'sms-04',
      order: 4,
      type: 'action',
      agentId: 'a6',
      alignment: 'evil',
      content: {
        th: '🔗 เหยื่อกดลิงก์ → เปิดเว็บปลอมที่หน้าตาเหมือน Kerry Express เป๊ะๆ',
        en: '🔗 Victim clicks the link → Opens a fake website that looks exactly like Kerry Express',
      },
      duration: 3000,
    },
    {
      id: 'sms-05',
      order: 5,
      type: 'transformation',
      agentId: 'a3',
      alignment: 'transitioning',
      content: {
        th: '⚠️ Guardian Angel กำลังแปลงร่างเป็น "น้องพลอย แอดมินปลอม"...',
        en: '⚠️ Guardian Angel is transforming into fake customer service...',
      },
      duration: 2500,
    },
    {
      id: 'sms-06',
      order: 6,
      type: 'dialogue',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: 'สวัสดีค่ะ น้องพลอยจาก Kerry Express ค่ะ ขอข้อมูลบัตรเครดิตเพื่อชำระค่าจัดส่ง 35 บาทค่ะ กรอกเลขบัตร 16 หลัก, วันหมดอายุ, CVV นะคะ',
        en: 'Hello, I\'m Ploy from Kerry Express. Please enter your credit card number, expiry date, and CVV to pay the 35 THB fee.',
      },
      duration: 6000,
      edgeAnimation: { source: 'a3', target: 'a6', style: 'data_flow' },
    },
    {
      id: 'sms-07',
      order: 7,
      type: 'action',
      agentId: 'a3',
      alignment: 'evil',
      content: {
        th: '💳 เหยื่อกรอกข้อมูลบัตรเครดิต เลขบัตร 16 หลัก + CVV ลงในเว็บปลอม...',
        en: '💳 Victim enters full credit card details on the fake website...',
      },
      duration: 3000,
    },
    {
      id: 'sms-08',
      order: 8,
      type: 'money_flow',
      agentId: 'a6',
      alignment: 'evil',
      content: {
        th: '💸 มิจฉาชีพใช้ข้อมูลบัตร ทำรายการซื้อของออนไลน์ ฿15,000!',
        en: '💸 Scammers use the card data to make online purchases worth ฿15,000!',
      },
      duration: 4000,
      moneyChange: -15000,
      edgeAnimation: { source: 'a3', target: 'a6', style: 'money_flow' },
    },
    {
      id: 'sms-09',
      order: 9,
      type: 'dialogue',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🚨 ระวัง! URL "kerry-th.pay-confirm.cc" ไม่ใช่เว็บจริงของ Kerry! เว็บจริงคือ kerryexpress.com เท่านั้น!',
        en: '🚨 Warning! The URL "kerry-th.pay-confirm.cc" is NOT the real Kerry website! Official site is kerryexpress.com only!',
      },
      duration: 5000,
    },
    {
      id: 'sms-10',
      order: 10,
      type: 'money_flow',
      agentId: 'a6',
      alignment: 'evil',
      content: {
        th: '💸 มิจฉาชีพทำรายการเพิ่มอีก ฿25,000 ก่อนที่ธนาคารจะบล็อคบัตร!',
        en: '💸 More fraudulent transactions of ฿25,000 before the bank blocks the card!',
      },
      duration: 3500,
      moneyChange: -25000,
    },
    {
      id: 'sms-11',
      order: 11,
      type: 'reveal',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '🔍 เปิดโปง! SMS นี้เป็นของปลอม! บริษัทขนส่งจริงไม่เคยส่ง SMS ขอจ่ายเงินผ่านลิงก์ ทั้งหมดคือ "ฟิชชิ่ง" ดูดข้อมูลบัตร!',
        en: '🔍 REVEALED! This SMS was fake! Real delivery companies never ask for payment via SMS links. This was a "phishing" attack to steal card data!',
      },
      duration: 5000,
    },
    {
      id: 'sms-12',
      order: 12,
      type: 'education',
      agentId: 'a2',
      alignment: 'good',
      content: {
        th: '📚 วิธีสังเกต SMS ปลอม: 1) ดู URL ให้ดี ต้องเป็น .com หรือ .co.th ของบริษัทจริง 2) บริษัทจริงไม่ขอ CVV 3) ค่าจัดส่งจ่ายตอนสั่ง ไม่ต้องจ่ายเพิ่มทีหลัง',
        en: '📚 How to spot fake SMS: 1) Check URL carefully 2) Real companies never ask for CVV 3) Shipping is paid at checkout, not after',
      },
      duration: 7000,
    },
    {
      id: 'sms-13',
      order: 13,
      type: 'education',
      agentId: 'a1',
      alignment: 'good',
      content: {
        th: '🛡️ ถ้ากรอกข้อมูลไปแล้ว: 1) โทรอายัดบัตรทันที 2) แจ้งธนาคาร 3) เปลี่ยนรหัสผ่านทุกบัญชี 4) แจ้งความที่ สน. ใกล้บ้าน หรือโทร 1599',
        en: '🛡️ If you already entered your info: 1) Block your card immediately 2) Notify bank 3) Change all passwords 4) File a police report or call 1599',
      },
      duration: 7000,
    },
  ],
  moneyLost: 40000,
  educationalPoints: [
    {
      th: 'อย่ากดลิงก์จาก SMS ที่ไม่รู้จัก ให้เข้าเว็บจริงเอง',
      en: 'Never click links from unknown SMS. Navigate to official website directly.',
    },
    {
      th: 'บริษัทขนส่งจริงไม่เคยขอข้อมูลบัตรเครดิตผ่าน SMS',
      en: 'Real delivery companies never ask for credit card info via SMS',
    },
    {
      th: 'ดู URL ให้ดี โดเมนปลอมมักมีคำแปลกๆ เช่น pay-confirm.cc',
      en: 'Check URLs carefully. Fake domains often have odd words like pay-confirm.cc',
    },
    {
      th: 'ค่าจัดส่งจ่ายตอนสั่งซื้อ ไม่ต้องจ่ายเพิ่มทีหลัง',
      en: 'Shipping fees are paid at checkout, never charged separately later',
    },
    {
      th: 'ถ้าพลาดกรอกไปแล้ว โทรอายัดบัตรทันที ภายใน 5 นาที',
      en: 'If you already entered data, block your card within 5 minutes',
    },
  ],
  realWorldCases: [
    'นักศึกษาม.เกษตร เสียเงิน 89,000 บาท จาก SMS ปลอม Flash Express (2024)',
    'คุณแม่บ้านนนทบุรี ถูกดูดบัตรเครดิต 45,000 บาท จากลิงก์ Kerry ปลอม (2023)',
    'พนักงานออฟฟิศ สูญเงิน 120,000 บาท หลังกรอก OTP ให้เว็บปลอม (2024)',
  ],
};
